### ISSUE TITLE
Static URL in Decryptor.cs

### ISSUE THREAD

**Issue by jioblack** [KasperSvendsenGit/Decrypt-Pluralsight-Videos#1]
This error is thrown when attempting to use the decryptor.

Start to decrypt all courses...
Cannot find the database path.
Error occured: Attempted to access a path that is not on the disk.
   at DecryptPluralSightVideos.Decryptor.DecryptAllFolders(String folderPath, String outputFolder) in E:\Work\DecryptPl
uralSightVideos\DecryptPluralSightVideos\Decryptor.cs:line 100
   at DecryptPluralSightVideos.Program.Main(String[] args) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos
\Program.cs:line 36

**Comment by KasperSvendsenGit** [comment]
Can you post the command you tried to run. It should be something like: 

DecryptPluralSightVideos.exe /F "REF1" /DB "REF2" /OUT "REF3"

REF1: Path to downloaded courses, default is C:\Users\username\AppData\Local\Pluralsight\courses

REF2: Path to pluralsight database, default is C:\Users\username\AppData\Local\Pluralsight\pluralsight.db

REF3: Path to output decrypted files.


Optional flags:
/TRANS - Generates subtitles file
/RM - Removes courses from database once decrypted
/HELP for help.

**Comment by knight6700** [comment]
i have this issue

**Comment by KasperSvendsenGit** [comment]
> i have this issue

Are you sure you have entered all the parameters correctly? Can you reply with the command that's causing the error.

**Comment by knight6700** [comment]
yes i fixed it when i have created empty folder
