### ISSUE TITLE
Videos can't be render

### ISSUE THREAD

**Issue by knight6700** [KasperSvendsenGit/Decrypt-Pluralsight-Videos#2]
after decrypt videos 
when open can't be render

**Comment by KasperSvendsenGit** [comment]
What do you mean? After the decryption you should have .mp4 (if I recall), are you having trouble with playback or are you not getting playable files like .mp4 files?

**Comment by SolosoftNL** [comment]
Hi Kasper,

i've got the same problem. Trouble with playback. Message "This files have properties that can't be read"
This is since May 2020 :(

**Comment by RodrigoGiroto1977** [comment]
Hi! I am having the same issue. The exe seems to work the same way, pick up info from the DB, convert the file to .Mp4 with the SRT file and copy to the destination informed by the user and delete the curse for the local cache. The project still working like a charm, but we can't open the output file.

There are a lot of Mp4 files but they can't run anymore, seems corrupted The MP4 sizes also seems to be according to the length of the video. I tried to open using Windows media player :( and VLC player. WMP gives the following error: 

"Windows Media Player cannot play the file. The Player might not support the file type or might not support the codec that was used to compress the file."

I could bet Pluralsight people change any configuration on the file to intentionally damage the output.

**Comment by matthieuscerri** [comment]
Hi there, 

I am having the same issue with playback...

Do you think you can fix this ?

Thank you very much for this app :)

**Comment by MahmoudIbrahiim** [comment]
I have the same issue

**Comment by miladashrafi** [comment]
Same Issue, SRT is well, but MP4 not playing!

**Comment by KasperSvendsenGit** [comment]
added disclaimer. "I am not the original programmer for this project. All software is provided as is. The original user took down their repo during a Pluralsight free month in april 2020."
