### ISSUE TITLE
Unfortunately, its no longer working !

### ISSUE THREAD

**Issue by SamRepository** [KasperSvendsenGit/Decrypt-Pluralsight-Videos#3]
It looks like Pluralsight has updated the encryption algorithm. Decryption is complete but videos won't open (file can't be rendered)!

**Comment by SolosoftNL** [comment]
yes, we know, it's a known issue. but the developer (aka kasper) won't respond to our issue reports. He has only give an reaction a day after the issue was reported, so he is aware. But no futher action..

**Comment by KasperSvendsenGit** [comment]
Hi @SolosoftNL @SamRepository 
I'm not the original developer of the program. I cloned it during April when Pluralsight had a free month promotion. The original developer has removed their repository and so I can't credit them... 
I unfortunately don't have the skill to continue development on this project.

**Comment by nabilnaim** [comment]
anyone find a solution for this issue
