### ISSUE TITLE
not work can update

### ISSUE THREAD

**Issue by mahdisky** [KasperSvendsenGit/Decrypt-Pluralsight-Videos#6]
not working
can you update?

**Comment by mrvogiacu** [comment]
> not working
> can you update?

try it

`https://github.com/dhorseman1710/Decrypt-PluralSight-GUI`

**Comment by RiboRabbit** [comment]
Thx bro you are life saver

> > not working
> > can you update?
> 
> try it
> 
> `https://github.com/dhorseman1710/Decrypt-PluralSight-GUI`

Thx bro you are life saver

**Comment by KasperSvendsenGit** [comment]
Resolved
